# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Install dependencies without running prepare scripts
COPY package.json package-lock.json tsconfig.json ./
RUN npm install --ignore-scripts

# Copy source and build
COPY src ./src
RUN npm run build

# Default command (overridden by MCP host)
CMD ["node", "build/index.js"]
